spring:
  application:
    name: crypto-trading-signal-function
  cloud:
    function:
      scan:
        packages: com.trading.signal.functions
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

sma:
  shortPeriod: 9
  longPeriod: 21
ema:
  shortPeriod: 12
  longPeriod: 26
rsi:
  period: 14
bbands:
  period: 20
  stddev: 2
macd:
  fastPeriod: 12
  slowPeriod: 26
  signalPeriod: 9
lindamacd:
  fastPeriod: 3
  slowPeriod: 10
  signalPeriod: 16
obv:
  maperiod: 14
stoch:
  fastKPeriod: 14
  slowKPeriod: 3
  slowDPeriod: 3
turtle:
  period: 14
crypto-data:
  apiEndpoint: https://api.binance.com