INSERT INTO oneday(symbol,
    signaltime     ,
    buystrength    ,
    sellstrength   ,
    bollingerbands ,
    ema            ,
    sma            ,
    macd           ,
    obv            ,
    rsi            ,
    rsidivergence  ,
    stochastic     ,
    engulfingcandle,
    lindamacd,
    turtlesignal,
    hammershootingcandle,
    version)
VALUES('BTCUSDT',1727523225, 'STRONG', 'LOW' ,'BUY','BUY', 'SELL', 'BUY', 'SELL', 'NONE', 'NONE', 'SELL', 'NONE', 'SELL', 'NONE', 'NONE', 0);

INSERT INTO onehour(symbol,
    signaltime,
    buystrength    ,
    sellstrength   ,
    bollingerbands ,
    ema            ,
    sma            ,
    macd           ,
    obv            ,
    rsi            ,
    rsidivergence  ,
    stochastic     ,
    engulfingcandle,
    lindamacd,
    turtlesignal,
    hammershootingcandle,
    version)
VALUES('BTCUSDT',1727523225, 'MEDIUM','STRONG', 'BUY','BUY', 'SELL', 'BUY', 'SELL', 'NONE', 'NONE', 'SELL', 'NONE', 'SELL', 'NONE', 'NONE', 0);

INSERT INTO fourhour(symbol,
     signaltime,
     buystrength    ,
     sellstrength   ,
     bollingerbands ,
     ema            ,
     sma            ,
     macd           ,
     obv            ,
     rsi            ,
     rsidivergence  ,
     stochastic     ,
     engulfingcandle,
     lindamacd,
     turtlesignal,
     hammershootingcandle,
     version)
VALUES('BTCUSDT',1727523225, 'LOW' ,'STRONG','BUY','BUY', 'SELL', 'BUY', 'SELL', 'NONE', 'NONE', 'SELL', 'NONE', 'SELL', 'NONE', 'NONE', 0);